### ISSUE TITLE
psutil ImportError

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#63]
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:56)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scooby import Report
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bane/Software/personal/scooby/scooby/__init__.py", line 18, in <module>
    from scooby.report import Report, get_version
  File "/Users/bane/Software/personal/scooby/scooby/report.py", line 16, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
>>>
```

After install `psutil`, here is my Report:

```
--------------------------------------------------------------------------------
  Date: Wed Nov 24 17:33:06 2021 MST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 32.0 GiB
       Environment : Python
       File system : apfs

  Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:56)
  [Clang 11.1.0 ]

             numpy : 1.21.4
             scipy : 1.7.3
           IPython : 7.29.0
        matplotlib : 3.5.0
            scooby : 0.5.7
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
This was install by `pip install -e .` in a fresh conda env

**Comment by banesullivan** [comment]
#61 introduced the breaking change. This will need to be an opt-in feature as `psutil` is currently an extra requirement.

**Comment by banesullivan** [comment]
@PythonFZ, would you be up for fix this?

**Comment by banesullivan** [comment]
Our CI should have caught this.
