### ISSUE TITLE
textwrap AttributeError: 'NoneType' object has no attribute 'expandtabs'

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/scooby#95]
```
$ python -c "import pyvista;print(pyvista.Report())"
  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/scooby/report.py", line 298, in __repr__
    for txt in textwrap.wrap(self._mkl_info, self.text_width - 4):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 387, in wrap
    return w.wrap(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 359, in wrap
    chunks = self._split_chunks(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 345, in _split_chunks
    text = self._munge_whitespace(text)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/textwrap.py", line 154, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
AttributeError: 'NoneType' object has no attribute 'expandtabs'
Error: Process completed with exit code 1.
```

**Comment by prisae** [comment]
@banesullivan - feel free to re-open if it did not fix the issue.
